option(WITH_TESTING "Build with unit tests" OFF)
option(WITH_PERFORMANCE_TESTING "Build with performance tests" OFF)
if (WITH_TESTING OR WITH_PERFORMANCE_TESTING)
  enable_testing()
  set(WITH_STATIC_LIB ON)
  set(BOOST_TEST_DEPENDENCIES unit_test_framework)
  option(PERFORMANCE_TEST_SAME_SERVERS "Use the same servers throughout the whole performance test" OFF)
endif (WITH_TESTING OR WITH_PERFORMANCE_TESTING)
