option(WITH_TESTING "Build with unit tests" OFF)
option(WITH_PERFORMANCE_TESTING "Build with performance tests" OFF)
option(WITH_STATIC_LIB "Build with a static library" OFF)
if (WITH_TESTING)
  set(WITH_STATIC_LIB ON)
  set(UNIT_TEST_FRAMEWORK unit_test_framework)
endif (WITH_TESTING)
